# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

future: false
show_drafts: false

# Define the display between the program block / adding a lecture contact form block.
program_active: false

# Define if there's lecturers in the camp.
lecturers: false
